JqueryAjaxKullanimi/Models/AjaxTestModel.cs
namespace JqueryAjaxKullanimi.Models
{
    using System.Data.Entity;

    public partial class AjaxTestModel : DbContext
    {
        public AjaxTestModel()
            : base("name=AJTModel")
        {
        }

        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<County> Counties { get; set; }
        public virtual DbSet<Product> Products { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
        }
    }
}

JqueryAjaxKullanimi/Models/City.cs
using System.Collections.Generic;

namespace JqueryAjaxKullanimi.Models
{
    //[Serializable]
    public class City
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public virtual ICollection<County> Counties { get; set; }
    }
}

JqueryAjaxKullanimi/Models/County.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace JqueryAjaxKullanimi.Models
{
    // [Serializable]
    public class County
    {
        public int ID { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        public int? City_ID { get; set; }
        [ForeignKey("City_ID")]
        public virtual City City { get; set; }
    }
}

JqueryAjaxKullanimi/Models/Product.cs
using System.ComponentModel.DataAnnotations;

namespace JqueryAjaxKullanimi.Models
{
    public class Product
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Ürün adı boş bırakılamaz")]
        [StringLength(maximumLength: 120, ErrorMessage = "Error Message")]
        public string Name { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
    }
}

JqueryAjaxKullanimi/Models/dtos/CityDto.cs
namespace JqueryAjaxKullanimi.Models.dtos
{
    public class CityDto
    {
        //cdto yerine kullanılabilecek bir data transfer object () sınıf oluşturuyoruz, var şeklinde kullanılmazsa bu dto kulanılır çünkü ajax virtual tablolu sınıflarsda sorn yaratıyor.
        public int ID;
        public string Name;
    }
}

JqueryAjaxKullanimi/Controllers/DefaultController.cs
using JqueryAjaxKullanimi.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace JqueryAjaxKullanimi.Controllers
{
    public class DefaultController : Controller
    {
        AjaxTestModel db = new AjaxTestModel();
        // GET: Default
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult SehirGetir()
        {
            return View();
        }
        [HttpGet]
        public ActionResult SehirIlceSec()
        {
            ViewBag.City_ID = new SelectList(db.Cities, "ID", "Name");
            ViewBag.County_ID = new SelectList(db.Counties.Where(x => x.City_ID == 1), "ID", "Name");
            return View();
        }

        public JsonResult LoadCounties(int cityid)
        {
            List<County> counties = db.Counties.Where(x => x.City_ID == cityid).ToList();
            var SelectListItems = counties.Select(x => new { ID = x.ID, Name = x.Name });
            return Json(SelectListItems, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult getCity(int id)
        {
            City c = db.Cities.FirstOrDefault(x => x.ID == id);
            var cdto = new { ID = c.ID, Name = c.Name };
            return Json(cdto, JsonRequestBehavior.AllowGet);
        }

    }
}

JqueryAjaxKullanimi/Controllers/ProductController.cs
using JqueryAjaxKullanimi.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace JqueryAjaxKullanimi.Controllers
{
    public class ProductController : Controller
    {
        AjaxTestModel db = new AjaxTestModel();
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public JsonResult GetProduct()
        {
            List<Product> products = db.Products.ToList();
            return Json(products, JsonRequestBehavior.AllowGet);
        }

        public JsonResult PostProduct(string name, string description, double price)
        {
            try
            {
                db.Products.Add(new Product() { Name = name, Description = description, Price = price });
                db.SaveChanges();
                return Json("1", JsonRequestBehavior.AllowGet);
            }
            catch (System.Exception)
            {

                return Json("0", JsonRequestBehavior.AllowGet);
            }
        }
    }
}

JqueryAjaxKullanimi/Views/Default/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/Assets/Bootstrap/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <div class="" id="div1" style="justify-content:center">
            <h3>Jquery Test Alanı</h3>
        </div>
        <button class="btn btn-success">Dışarıdan Veri Al</button>
        <div>
            <h2>Ajax : Asynchronus Javascript and XML</h2>
            <p>Browser Uygulamalarında backend ve ui arasında iletişim amacıyla kullanılır</p>
        </div>
    </div>
    <script src="~/Assets/jquery-3.7.1/jquery-3.7.1.min.js"></script>
    <script>
        $(document).ready(function () {
            $("button").click(function () {
                $("#div1").load("../../Dosyalar/ajaxtest.txt", function (donustxt, durumtxt, xhr) {
                    if (durumtxt == "success") { alert("Dosya başarıyla yüklendi"); }
                    if (durumtxt == "error") { alert("HATA: " + xhr.status + " - " + xhr.statusText); }
                });
            });
        });
    </script>
</body>
</html>

JqueryAjaxKullanimi/Views/Default/SehirGetir.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SehirGetir</title>
    <link href="~/Assets/Bootstrap/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <div style="margin-top:10px">
            <input type="type" id="sehirID" name="name" value="" class="" placeholder="Şehir İdsi Gir" />
            <input type="submit" id="sehirGetir" name="name" value="Şehir Getir" class="btn btn-success" />
            <br />
        </div>
        <div>
            <p>Şehir Idsi : <strong id="gelenSehirID"></strong></p>
            <p>Şehir Adı: <strong id="gelenSehirAdi"></strong></p>
        </div>
    </div>
   
    <script src="~/Assets/jquery-3.7.1/jquery-3.7.1.min.js"></script>
    <script src="~/Assets/Bootstrap/js/bootstrap.min.js"></script>
    <script>
        $(document).ready(function () {
            $("#sehirGetir").click(function () {
                $("#sehirID").css({ "border": "1px solid black" })
                var ID = $("#sehirID").val();
                if (ID != "") {
                    $.ajax({
                        url: '/Default/getCity/' + ID,
                        type: 'POST',
                        datatype: 'json',
                        success: function (data) {
                            $("#gelenSehirID").html(data.ID)
                            $("#gelenSehirAdi").html(data.Name)
                        },
                        error: function () {
                            alert("Hata Oluştu!")
                        }
                    })
                }
                else {
                    $("#sehirID").css({"border":"1px solid red"})
                }
                
            })
        })
    </script>
</body>
</html>

JqueryAjaxKullanimi/Views/Default/SehirIlceSec.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SehirIlceSec</title>
</head>
<body>
    <div> 
        @Html.DropDownList("city_ID", null, htmlAttributes: new { @id = "city_ID" })
        <br />
        @Html.DropDownList("county_ID", null, htmlAttributes: new { @id = "county_ID" })
    </div>
    <script src="~/Assets/jquery-3.7.1/jquery-3.7.1.min.js"></script>
    <script>
        $(document).ready(function () {
            $("#city_ID").change(function () {
                var cid = $(this).val();
                $.ajax({
                    type: "POST",
                    url:'@Url.Action("LoadCounties","Default")',
                    data: { cityid: cid },
                    success: successFunction,
                    error: errorFunction
                });
                function successFunction(data){
                    var droplist = $("#county_ID");
                    droplist.empty();
                    $.each(data, function (index, item) {
                        droplist.append($('<option/>', { value: item.ID, text: item.Name }));
                    });
                }
                function errorFunction() {
                    alert("Seçim Hatası");
                }
            });
        });
    </script>
</body>
</html>

JqueryAjaxKullanimi/Views/Product/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/Assets/Bootstrap/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <div class="card mt-3 mb-3">
            <div class="card-body">
                <div>
                    <label>İsim</label>
                    <input type="text" name="name" class="form-control" id="tb_name"/>
                </div>
                <div>
                    <label>Açıklama</label>
                    <input type="text" name="name" class="form-control" id="tb_description" />
                </div>
                <div>
                    <label>Fiyat</label>
                    <input type="text" name="name" class="form-control" id="tb_price"/>
                </div>
                <div class="mt-2">
                    <input type="button" id="postProduct" name="name" value="Ürün Ekle" class="btn btn-primary" />
                </div>
            </div>
            
        </div>
        <div class="card">
            <div class="card-header bg-secondary">
                <h4 class="card-title">Ürünler</h4>
            </div>
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>İsim</th>
                        <th>Fiyat</th>
                        <th>Açıklama</th>
                    </tr>
                </thead>
                <tbody id="tableBody">
                </tbody>
            </table>
        </div>
    </div>
    <script src="~/Assets/jquery-3.7.1/jquery-3.7.1.min.js"></script>
    <script src="~/Assets/Bootstrap/js/bootstrap.min.js"></script>
    <script>
        $(document).ready(function () {
            function loadProducts() {
                $.ajax(
                {
                    url:'@Url.Action("GetProduct", "Product")',
                    type: 'GET',
                    success: function(data) {
                        var body = $("#tableBody");
                        console.log(data);
                        body.empty();
                        $.each(data, function (i, product) {
                            body.append(
                                "<tr><td>" + product.ID + "</td><td>" + product.Name + "</td><td>" + product.Price + "</td><td>" + product.Description +"</td><td><input type='button' value='Sil' class='btn btn-danger' id='sil' data-val='"+product.ID+"'></td></tr>"
                            );
                        });
                    }
                })
            }
            loadProducts();
            $("#postProduct").click(function () {
                var name = $("#tb_name").val();
                var description = $("#tb_description").val();
                var price = $("#tb_price").val();
                $.ajax({
                    url: '@Url.Action("PostProduct", "Product")',
                    type: "POST",
                    data: { name: name, description: description, price: price },
                    success: function (response) {
                        if (response=="1") {
                            loadProducts();
                        }
                        else {
                            alert("Success Başarısız!");
                        }
                    },
                    error: function () { alert("Hata!") }
                })

            })

            $("#tableBody").on("click", "#sil", function () {
                var pid = $(this).attr("data-val");
                console.log(pid)
            });
        });
    </script>
</body>
</html>